### ISSUE TITLE
input impedance problem

### ISSUE THREAD

**Issue by SJetandKara** [ojg/thatmicpre#1]
what is the input impedance of this preamp？
maybe by tweaking the input impedance we can get different sound features like ISA preamp(which provided input impedance options like 600Ω/1100Ω/2.4kΩ/6.8kΩ)？

**Comment by ojg** [comment]
The input impedance with the values shown in the schematic is ~2kohm differentially. 

It's (R5+R6) || (R1+R2). So you can tune it easily by changing R1 and R2.
